# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wine_varieties.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14wine_varieties.proto\x12\x02pb\"#\n\x11WineReviewRequest\x12\x0e\n\x06review\x18\x01 \x01(\t\"%\n\x12WineReviewResponse\x12\x0f\n\x07variety\x18\x01 \x01(\t2X\n\x15WineClassifierService\x12?\n\x0eGetWineVariety\x12\x15.pb.WineReviewRequest\x1a\x16.pb.WineReviewResponseB\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wine_varieties_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _WINEREVIEWREQUEST._serialized_start=28
  _WINEREVIEWREQUEST._serialized_end=63
  _WINEREVIEWRESPONSE._serialized_start=65
  _WINEREVIEWRESPONSE._serialized_end=102
  _WINECLASSIFIERSERVICE._serialized_start=104
  _WINECLASSIFIERSERVICE._serialized_end=192
# @@protoc_insertion_point(module_scope)
